### ISSUE TITLE
Got ECONNREFUSED on node 18

### ISSUE THREAD

**Issue by Raynos** [mmarchini-oss/node-observe#24]
$ pnpm observe heap-profile -d 60 -p 253342
Error: connect ECONNREFUSED ::1:9229
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 9229
}

I believe nodejs 18 made a breaking change to default to ipv6 which is dumb af.

**Comment by mmarchini** [comment]
yeah, there's a commit to fix it already, I just need to publish it. In the meantime you can workaround the issue with `pnpm observe heap-profile -d 60 -p 253342 --host 127.0.0.1`

**Comment by mmarchini** [comment]
should be fixed on v2.0.0

**Comment by Raynos** [comment]
Awesome. Thank you
